name: Lint Code Workfow

on:
  pull_request:
    - opened
    - edited
    - synchronize

jobs:
  lint:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang clang-tidy clang-format cppcheck

    - name: Run clang-tidy
      run: |
        mkdir -p build && cd build
        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
        ln -s $(pwd)/compile_commands.json ../
        cd ..
        run-clang-tidy -p build

    - name: Run cppcheck
      run: |
        cppcheck --enable=all --suppress=missingIncludeSystem --inline-suppr src/

